### ISSUE TITLE
group setting issues

### ISSUE THREAD

**Issue by JamieKG** [DawnFire-Realms/CommunityBridge#126]
hi im using zpermissions and xenforo and if I set a player to the builder group ingame in CommunintyBridge it will list them as having the member group in the player.yml even tho they are not in it altho they do inherit their permissions

``` yaml
webapp:
  primary-group-id: ''
  group-ids: []
permissions-system:
  primary-group-name: ''
  group-names:
  - member
  - builder
```

also when it updates the mysql entry of the secondary group it dose not separate the groups with a ","

my config.yml
http://pastebin.com/X3C3Bixx
Thanks JamieKG
