### ISSUE TITLE
Problem with Wordpress and BuddyPress

### ISSUE THREAD

**Issue by X00LA** [DawnFire-Realms/CommunityBridge#143]
Hi,

I use WordPress for my homepge and want to synchronise it with CommunityBridge.
I use BuddyPress for the groups and there's some little problems.

BuddyPress uses 2 tables. 1 for the groups and 1 for the group members. And this is the problem.

I tested multiple configs, but none works for me. The problem is, that in the group table is no user id column and CB needs it. When i startup my server i get some errormessages. When i logeed in in my server CB says it has synchonised the account with the webpage, but nothing changes in the database and on the page.

Here's my config:

``` yaml
app-group-config:
  # If the web application has a primary group/role feature, configure it here.
  primary:
    enabled: true
    # The table that contains the primary group ID.
    table-name: wp_bp_groups

    # The column on the table that contains the user ID.
    #user-id-column: 

    # If the primary group is stored in a key-value pair, set this to true.
    uses-key: false

    # The column that the primary group ID is stored in. If uses-key is true,
    # this is the column that the "value" of the key-value pair is stored in.
    group-id-column: group_id

    # If you set uses-key to true, then set the following three settings:
    # Key name for the key-value pair.
    key-name:
    # Column that the key name is in
    key-column:

  # If the web application has a secondary groups feature, configure it here.
  secondary:
    enabled: true
    # The table that contains the secondary groups.
    table-name: wp_bp_groups_members

    # The column on the table that contains the user ID.
    user-id-column: user_id

    # Storage method. Set to one of the following:
    # - single: All the group ids in a single row & column separated by the
    #           delimiter specified below.
    # - key-value: All the group ids are in a single row & column, separated
    #              by the delimiter specified below, on a table that stores
    #              its data in key-value pairs
    # - multiple-key-value: Group IDs are stored on a table of key-value pairs,
    #                    where the key name can appear in multiple rows.
    # - junction: The table can contain multiple rows for a given user_id,
    #             each with their own group_id.
    storage-method: junction

    # The column that the group ID(s) are stored in:
    # (For the key-value method, this is the 'value' column)
    group-id-column: group_id

    # For single-column or key-value storage methods, the delimiter/separator
    # that separates the group IDs:
    # (ignored for junction and multiple-key-value storage method)
    group-id-delimiter: ','

    # For the key-value storage method:
    # (ignored for the junction and single methods)
    # Key name for the key-value pair.
    key-name:
    # Column that the key name is in
    key-column:

# Simple Synchronization Configuration
# NOTE: If you wish to utilize the primary group synchronization feature and
#       your permissions system does not support primary groups, then you must
#       list groups you wish to be synchronized into the web applications
#       primary group field in the "groups-treated-as-primary" setting. The
#       permissions systems that this applies to are: bPerms, PermissionsBukkit,
#       PermissionsEx, Vault, and zPermissions.
simple-synchronization:
  # Set this to true for simple synchronization
  enabled: true

  # Controls the "direction" of synchronization.
  # Options are: two-way, web-application, or minecraft.
  # - two-way: Changes on either side are synchronized to the other.
  # - web-application: Changes made in the web-application are
  #   synchronized to the Minecraft server.
  # - minecraft: Changes made in Minecraft are synchronized to the
  #   web-application.
  direction: two-way

  # If player hasn't been seen before on server, CommunityBridge will use this
  # setting to determine the direction of the synchronization. 'web-application'
  # is the only option available at this time.
  first-direction: web-application

  # Set this to true if you want the player to be notified when their primary
  # group changes.
  primary-group-change-notify: true

  # This is a safety net. Since CommunityBridge directly modifies group
  # membership information, there is a risk that a misconfiguration could
  # cause the main administrative account (e.g. super-user) of a webapp to not
  # have administrative privileges to the forum, potentially leaving the forum
  # in a state where it cannot be administered. To protect against this
  # possibility, provide the user-id of the main administrative account of the
  # web application here. Generally, this is the account created when the web
  # application was installed. For this user-id, group changes will not be
  # synchronized from Minecraft to the web application, that is, the
  # synchronization for this user will be as if direction was set to
  # 'web' (see above). Be absolutely sure this user-id is your super-user
  # all-access administrative account.  
  super-user-user-id: '7'

  # If you're using primary group synchronization and a permissions system that
  # does NOT have the notion of primary groups (bPerms, PermissionsBukkit,
  # PermissionsEx, Vault) you must list permission group names that you wish to
  # be synchronized into the user's primary group field on the web application
  # here. Be sure to include these groups in the group-mapping as well.
  # Sample: groups-treated-as-primary: [guest, member, premium]
  groups-treated-as-primary: [1, 2, 3, 4, 5, 6, 7, 8]

  # List groups and group IDs to be synchronized here. On the left side of
  # the colon put a web application's group ID. On the right side of the colon
  # put the corresponding permissions group name. Only list group IDs and
  # group names you wish to be synchronized.

  # NOTE: GroupManager will not create groups on the fly. So any groups you
  #       specify here must already exist. That is, you need to have used
  #       mangadd <groupname>.
  # NOTE: Regarding ladders(promotions/inherited groups): Either ALL of the
  #       groups that are part of a ladder need to have entries on this table
  #       and have corresponding group on the web application or NONE of them
  #       should be on this list. It may be that you want to use the
  #       unregistered/registered group settings instead. 
  group-mapping:


ban-synchronization:
  enabled: true
  # If your web application stores banned users in a group, set this to group
  # otherwise set it to table.
  method: group
  # If method is 'group' above, fill in the group-ids for the ban group(s)
  # here. Otherwise, fill in table-name, banned-user-id-column,
  # ban-reason-column, etc. below...
  ban-group-ids: [8]

  # Settings for table method...
  # Name of the table that holds ban information for your web application
  table-name: wp_bp_groups_members
  # Column that contains the user ID of the banee.
  banned-user-id-column: user_id
  # The column containing the reason for the ban. Leave blank if your web
  # application does not support this.
  ban-reason-column: comments
  # The column containing the ban start time (systime expected). Leave blank
  # if your application does not support this.
  ban-start-column:
  # The column containing the ban end time (systime expected). Leave blank
  # if your application does not support this.
  ban-end-column:
```

These are my server log:

```
Console : Information: [CommunityBridge] Enabling CommunityBridge v2.1.3.341
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Detected locale: en
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : WARNING: [CommunityBridge] The achievements.yml file is empty.
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Log level                            : config
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Plugin metrics enabled               : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Use achievements                     : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Permissions system                   : PEX
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Economy enabled                      : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Autosync                             : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Autosync every                       : 20 minutes
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Synchronize during join event        : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Synchronize during quit event        : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Application url                      : http://www.chroniken-von-deria.eu
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Date Format                          : yyyy-MM-dd hh:mm:ss a
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Database hostname                    : localhost
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Database port                        : 3306
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Database name                        : minecraft
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Database username                    : Minecrafter
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking auto reminder                : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking auto reminder every          : 10 minutes
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking notify registered            : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking notify unregistered          : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking kick unregistered            : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking unregistered group           : 1
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking registered group             : 2
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking notify player of group       : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking reg former unregistered only : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking uses key-value pair          : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking table name                   : wp_users
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking user ID column               : ID
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Linking player name column           : user_login
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Avatars config enabled               : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Post count config enabled            : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Post count user ID column            : null
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Post count post count column         : null
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Require avatars                      : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Require minimum posts                : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Tracking statistics                  : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Primary group table                  : wp_bp_groups
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Primary group user id column         : 
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Primary group group id column        : group_id
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Primary group uses key               : false
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Secondary group table                : wp_bp_groups_members
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Secondary group user id column       : user_id
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Secondary group group id column      : group_id
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Secondary group storage method       : junction
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Simple synchronization enabled       : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Simple synchronization direction     : two-way
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Simple synchronization firstdirection: web-application
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Simple synchronization notification  : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Simple synchronization P-groups      : [1, 2, 3, 4, 5, 6, 7, 8]
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Ban synchronization enabled          : true
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Ban synchronization method           : group
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Ban synchronization group IDs        : [8]
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Ban synchronization table name       : 
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Ban synchronization user ID column   : user_id
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Ban synchronization reason column    : comments
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Ban synchronization start time column: 
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : Information: [CommunityBridge] Ban synchronization end time column  : 
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : SEVERE: [CommunityBridge] Error while checking 'app-group-config.primary.user-id-column' set to '': Empty column name.
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : SEVERE: [CommunityBridge] Error while checking 'app-group-config.primary.group-id-column' set to 'group_id': Column does not exist.
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : SEVERE: [CommunityBridge] The super-user's user ID not found.
Console : Mar 01, 2014 2:41:55 PM org.bukkit.plugin.PluginLogger log
Console : SEVERE: [CommunityBridge] Simple synchronization disabled due to prior errors.
Console : Mar 01, 2014 2:41:56 PM org.bukkit.plugin.java.JavaPluginLoader enablePlugin
Console : SEVERE: Error occurred while enabling CommunityBridge v2.1.3.341 (Is it up to date?)
Console : java.lang.NumberFormatException: For input string: "Unknown"
Console :   at java.lang.NumberFormatException.forInputString(Unknown Source)
Console :   at java.lang.Integer.parseInt(Unknown Source)
Console :   at java.lang.Integer.parseInt(Unknown Source)
Console :   at org.communitybridge.utility.StringUtilities.compareVersion(StringUtilities.java:47)
Console :   at org.communitybridge.permissionhandlers.PermissionHandlerPermissionsEx.<init>(PermissionHandlerPermissionsEx.java:32)
Console :   at org.communitybridge.main.CommunityBridge.selectPermissionsHandler(CommunityBridge.java:436)
Console :   at org.communitybridge.main.CommunityBridge.activate(CommunityBridge.java:104)
Console :   at org.communitybridge.main.CommunityBridge.onEnable(CommunityBridge.java:70)
Console :   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250)
Console :   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:360)
Console :   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:390)
Console :   at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:391)
Console :   at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:327)
Console :   at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:517)
Console :   at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:490)
Console :   at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:433)
Console :   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:292)
Console :   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:621)
Console :   at java.lang.Thread.run(Unknown Source)
```

And these are the database tables:

Table wp_bp_groups (Grouptable)
http://i61.tinypic.com/r2t9ur.jpg|wp_bp_groups

Table wp_bp_groups_members (Membertable)
http://i58.tinypic.com/ilketl.jpg|wp_bp_groups_members

I hope you can help me to solve this issue.

Regards,

X00LA
