### ISSUE TITLE
Feature: Web secondary groups to be treated as primary.

### ISSUE THREAD

**Issue by hockeymikey** [DawnFire-Realms/CommunityBridge#179]
Forum: Xenforo
Permissions: PEX
Config: http://pastebin.com/gd69DYTU

Using a test account I created their account on the forum.  CB recognised it when the player (skiptoops) logged in and changed their in game rank to reflex the web rank.
They had a web rank of Sailor as the primary group.  Their PEX rank wasn't changed in the right way.

```
  3b0a9643-1171-48e0-b8fd-4f050f55e27f:
    group:
    - Sailor
    options:
      name: Paco33149
  d2a6c6ec-18ef-4c5a-8355-3296c67aeb57:
    group:
    - Stowaway
    - Sailor
```

The user in the permissions file for PEX was lacking their name which displayed their username as the default group (Stowaway) still until the options: name part was added in.  Also the Sailor rank was stacked on to the user's Stowaway rank rather than change the users rank to Sailor.

Thanks
