### ISSUE TITLE
Wordpress Config 1.7.9 Server Port Error

### ISSUE THREAD

**Issue by kingsblend** [DawnFire-Realms/CommunityBridge#196]
First github post ty. Here is my error on server start:

```
Error: Could not connect to MySQL server: Must specify port after ':' in connection string
```

I am hosting the server locally over hamachi. This IP here is the server IP and I have granted remote access to useres from all localhost and the hamachi IP. 

For testing purposes, the wordpress is hosted locally via xampp and all config is done vie phpmyadmin from http:// **.hamachi.ip.**

The full config if it helps. Anyone have any ideas?

```
# 
# Wordpress Config
db-host: **.***.***.**
db-port: 3306
db-database: ohmc
db-username: **
db-password: **
show-config: false
show-primary-group: false
registered-message: Registered Account, Linked to player Directory
unregistered-message: Unregistered Account - Please Register at YOURFORUM for access
unregistered-messagereminder: Just a reminder to visit YOURFOURM and register today!
kick-unregistered: true
multi-tables: true
multi-tables-use-key: true
use-banned-field: false
banlist-table:
  enabled:
  table:
  user-id-field:
  reason-field:
groups-table:
  enabled: false
  table: 
  user-id-field: 
  group-id-field: 
secondary-groups: 
permissions-system: PermissionsBukkit
auto-sync: true
auto-remind: false
auto-sync-every: 1200000
auto-remind-every: 600000
enable-basic-tracking: false
users-table:
  table: wp_users
  user-name-field: user_login
  user-id-field: ID
  groups-id-field: user_status
  secondary-groups-id-field: 
  banned-field:
  banned-users-group:
  default-group:
multi-table:
  table: wp_usermeta
  field-user-id-field: user_id
  field-key-field: meta_key
  field-key-value: meta_value
  field-value-field: mc_playername
profile-requirements:
  require-avatar: false
  require-avatar-message: 
  require-avatar-table: 
  require-avatar-user-id-field: 
  require-avatar-field: 
  require-minposts: false
  require-minposts-message: 
  require-minposts-count: 
  require-minposts-table: 
  require-minposts-user-id-field: 
  require-minposts-field: 
basic-tracking:
  table: cb_tracking
  field-onlinestatus-enabled: false
  field-onlinestatus-valueonline: 1
  field-onlinestatus-valueoffline: 0
  field-onlinestatus-key-value: mconlinestatus
  field-onlinestatus-field: field_14
  field-lastonline-enabled: true
  field-lastonline-key-value: mclastonline
  field-lastonline-field: field_15
  field-gametime-enabled: false
  field-gametime-key-value: mcgametime
  field-gametime-field: field_16
  field-totalxp-enabled: false
  field-totalxp-key-value: mctotalxp
  field-totalxp-field: field_18
  field-currentxp-enabled: false
  field-currentxp-key-value: mccurrentxp
  field-currentxp-field: field_17
  field-level-enabled: false
  field-level-key-value: mclevel
  field-level-field: field_19
  field-health-enabled: false
  field-health-key-value: mchealth
  field-health-field: field_20
  field-lifeticks-enabled: false
  field-lifeticks-key-value: mclifeticks
  field-lifeticks-field: field_21
  field-wallet-enabled: false
  field-wallet-key-value: mcwallet
  field-wallet-field: field_23
groups:
  '1': validating
  '2': guest
  '3': builder
  '6': moderator
  '4': admin
  '5': banned
```

My question is what can be causing this error? The ultimate goal is to integrate this into a user friendly wordpress plugin and learn java in the process. Ty in advance for all help.
