### ISSUE TITLE
Xenforo + Community Bridge + `xf_user_field_value` = [CommunityBridge] Not changing permissions group due to permissions system group name lookup failure for web application group ID: . Player <username> primary group state unchanged.

### ISSUE THREAD

**Issue by tonnic** [DawnFire-Realms/CommunityBridge#255]
Hi,
My usergroups won't synchronize.   I am using Xenforo and have the Minecraft username as a custom field in the user profile.

My player-user-linking: looks like
```
 # The name of the table which contains the columns:
  table-name: 'xf_user_field_value'

  # Column on the table that contains the user ID. Typically something like
  # user_id or member_id
  user-id-column: 'user_id'

  # If the player name is stored in a key-value pair of columns instead of
  # its own column, set this to true:
  uses-key: true

  # If you set 'linking-uses-key' to false, then set this to the column that
  # the playername is stored in. Otherwise, leave it empty.
  playername-column:

  # If you set 'linking-uses-key' to true, then set the key column, value
  # column, and the key-name here. Otherwise, leave these fields empty.
  key-name: 'minecraftname'
  key-column: 'field_id'
  value-column: 'field_value'
```

My app-group-config: looks like:
```
app-group-config:
  # If the web application has a primary group/role feature, configure it here.
  primary:
    enabled: true
    # The table that contains the primary group ID.
    table-name: 'xf_user'

    # The column on the table that contains the user ID.
    user-id-column: 'user_id'

    # If the primary group is stored in a key-value pair, set this to true.
    uses-key: false

    # The column that the primary group ID is stored in. If uses-key is true,
    # this is the column that the "value" of the key-value pair is stored in.
    group-id-column: 'user_group_id'

    # If you set uses-key to true, then set the following three settings:
    # Key name for the key-value pair.
    key-name:
    # Column that the key name is in
    key-column:

  # If the web application has a secondary groups feature, configure it here.
  secondary:
    enabled: true
    # The table that contains the secondary groups.
    table-name: 'xf_user'

    # The column on the table that contains the user ID.
    user-id-column: 'user_id'

    # Storage method. Set to one of the following:
    # - single: All the group ids in a single row & column separated by the
    #           delimiter specified below.
    # - key-value: All the group ids are in a single row & column, separated
    #              by the delimiter specified below, on a table that stores
    #              its data in key-value pairs
    # - multiple-key-value: Group IDs are stored on a table of key-value pairs,
    #                    where the key name can appear in multiple rows.
    # - junction: The table can contain multiple rows for a given user_id,
    #             each with their own group_id.
    storage-method: 'single'

    # The column that the group ID(s) are stored in:
    # (For the key-value method, this is the 'value' column)
    group-id-column: 'secondary_group_ids'

    # For single-column or key-value storage methods, the delimiter/separator
    # that separates the group IDs:
    # (ignored for junction and multiple-key-value storage method)
    group-id-delimiter: ','

    # For the key-value storage method:
    # (ignored for the junction and single methods)
    # Key name for the key-value pair.
    key-name:
    # Column that the key name is in
    key-column:

```

CommunityBridge doesn't know what user I am in, because in the app-group-config needs to get the username from the player-user-linking not from the xf_user group.   The problem is I can't use the table of 'xf_user_field_value' because there are no group names.  I need the user_id from 'xf_user_field_value' so that it can then cross reference it back to the xf_user group.... 

Has anyone else seen this and have this problem?   I really just want the user groups to sync!
