### ISSUE TITLE
GroupManager / phpBB setup issues.

### ISSUE THREAD

**Issue by blackmousepad** [DawnFire-Realms/CommunityBridge#32]
So I got this installed and configured, however I'm stuck. Whenever a user joins that has registered on the forums I get this in the logs...

02:11:39 [INFO] Group not found!
02:11:39 [INFO] /manuadd <player> <group> | optional [world]
02:11:39 [INFO] [CommunityBridge] Setting daplayer to group null
02:11:39 [INFO] [CommunityBridge] daplayer linked to Community User #56, Group: null

Here's my config for CommunityBridge. Any help would be super!

``` yaml
log-level: finest
permissions-system: GroupManager
db-host: localhost
db-port: 3306
db-database: phpbb
db-username: user
db-password: pass

show-primary-group: true
kick-unregistered: false
multi-tables: false
multi-tables-use-key: false
use-banned-field: false

group-synchronization:
  primary-group:
    enabled: true
    group-ids-to-ignore: []
    group-names-to-ignore: []

groups-table:
    enabled: false
    table: phpbb_user_group
    user-id-field: user_id
    group-id-field: group_id
secondary-groups: false
auto-sync: true
auto-every-unit: minutes
auto-sync-every: 20
auto-remind: true
auto-remind-every: 5
enable-basic-tracking: false

users-table:
  table: phpbb_users
  user-name-field: username_clean
  user-id-field: user_id
  groups-id-field: group_id
  default-group: 1

groups:
'12':'_MEMBERDONATE'
'1':'_GUEST'
'13':'_OWNER'
'10':'_MEMBERCHARTER'
'8':'_MOD'
'11':'_MEMBER'
'3':'_MEMBER'
'9':'_ADMIN'
```
