### ISSUE TITLE
SMF Configuration issues

### ISSUE THREAD

**Issue by paul1338** [DawnFire-Realms/CommunityBridge#35]
After completely configure community bridge v2.0.0.182 I get the following errors:

[SEVERE] [CommunityBridge] The super-user's user ID setting is not set.
[SEVERE] [CommunityBridge] Simple synchronization disabled due to prior errors.

but in my config it is set:

super-user-user-id: '1'

Any help would be appreciated!
Here is my config file (cut out the comments so it wasn't quite as long, if I cut anything out let me know):

```
#                  Community Bridge Configuration File
# -----------------------------------------------------------------------------

#                             General Settings
# -----------------------------------------------------------------------------
general:
  log-level: config

  plugin-metrics: true

  auto-every-unit: minutes

  auto-sync: false

  auto-sync-every: 20

  permissions-system: PEX

  application-url: localhost/emp/forums

#                             Database Settings
# -----------------------------------------------------------------------------
database:
  # Hostname for your MySQL Server
  hostname: localhost

  # MySQL Port
  port: 3306

  # Database Name
  name: db

  # Database Username
  username: user

  # Database Password
  password: pass

#                             Player Linking Settings
# -----------------------------------------------------------------------------
player-user-linking:

  kick-unregistered: false

  auto-remind: true

  auto-remind-every: 10

  notify-registered-player: true
  notify-unregistered-player: true

  unregistered-player-group:
  registered-player-group:
  notify-player-of-group: true

  registered-former-unregistered-only: true

  table-name: smf_themes

  user-id-column: id_member

  uses-key: true

  playername-column:

  key-name: cust_ign
  key-column: variable
  value-column: value

#                             Requirements
# -----------------------------------------------------------------------------
requirement:
  avatar:
    enabled: false
    table-name:
    user-id-column:
    avatar-column:
  minimum-posts:
    enabled: false
    table-name:
    user-id-column:
    post-count-column:
    post-count:

#                             Statistics Tracking
# -----------------------------------------------------------------------------
statistics:
  enabled: false
  table-name:
  user-id-column:
  uses-key: false

  key-column:
  value-column:

    online-status:
      enabled: false
      column-or-key-name:
      online-value:
      offline-value:
    last-online:
      enabled: false
      column-or-key-name:
      formatted-column-or-key-name:

    game-time:
      enabled: false
      column-or-key-name:
      formatted-column-or-key-name:

    level:
      enabled: false
      column-or-key-name:

    current-xp:
      enabled: false
      column-or-key-name:
      formatted-column-or-key-name:

    total-xp:
      enabled: false
      column-or-key-name:

    health:
      enabled: false
      column-or-key-name:

    lifeticks:
      enabled: false
      column-or-key-name:
      formatted-column-or-key-name:

    wallet:
      enabled: false
      column-or-key-name:

#                     Web Application Group Configuration
# -----------------------------------------------------------------------------
app-group-config:
  primary:
    enabled: true
    table-name: smf_members
    user-id-column: id_member
    uses-key: false
    group-id-column: id_group

    key-name:
    key-column:

  secondary:
    enabled: true
    table-name: smf_members

    user-id-column: id_member

    storage-method: single

    group-id-column: additional_groups

    group-id-delimiter: ','

    key-name:
    key-column:

simple-synchronization:
  # Set this to true for simple synchronization
  enabled: true

  direction: minecraft

  # Set this to true if you want the player to be notified when their primary
  # group changes.
  primary-group-change-notify: false

  super-user-user-id: '1'

  groups-treated-as-primary: ['Guest','Member','Veteran','Elder']

  group-mapping:
    '12' : 'Guest'
    '11' : 'Member'
    '10' : 'Veteran'
    '9'  : 'Elder'


```
