### ISSUE TITLE
Minecraft->webapp sync doesn't appear to be working correctly.

### ISSUE THREAD

**Issue by paul1338** [DawnFire-Realms/CommunityBridge#36]
Upon running /cbsyncall or /cbsync the webapp primary groups aren't updated. I'm not sure if this is due to a config error or not. When I run the command I get this in the server log:

```

[INFO] [CommunityBridge] (CONSOLE) Groups and/or statistics will be synchronized for all connected players.
[INFO] [CommunityBridge] SELECT `id_group` FROM `smf_members` WHERE `id_member` = '3'
[INFO] [CommunityBridge] SELECT `additional_groups` FROM `smf_members` WHERE `id_member` = '3'

```

Upon inspecting my player.yml file (under CommunityBridge\Players) I find that 
'primary-group-name:' is not set, but my current in game group is listed under 'group-names:'. Just wondering if that may be the culprit/config error on my part.

My config file (cut out some comments and features set to false so it wasn't quite as long, if I cut anything out let me know):

```

#                  Community Bridge Configuration File
# -----------------------------------------------------------------------------

#                             General Settings
# -----------------------------------------------------------------------------
general:
  log-level: all

  plugin-metrics: true

  auto-every-unit: minutes

  auto-sync: false

  auto-sync-every: 20

  permissions-system: PEX

  application-url: localhost/emp/forums

#                             Database Settings
# -----------------------------------------------------------------------------
database:
  # Hostname for your MySQL Server
  hostname: localhost

  # MySQL Port
  port: 3306

  # Database Name
  name: db

  # Database Username
  username: user

  # Database Password
  password: pass

#                             Player Linking Settings
# -----------------------------------------------------------------------------
player-user-linking:

  kick-unregistered: false

  auto-remind: true

  auto-remind-every: 10

  notify-registered-player: true
  notify-unregistered-player: true

  unregistered-player-group:
  registered-player-group:
  notify-player-of-group: true

  registered-former-unregistered-only: true

  table-name: smf_themes

  user-id-column: id_member

  uses-key: true

  playername-column:

  key-name: cust_ign
  key-column: variable
  value-column: value

#                             Requirements (false, removed)

#                             Statistics Tracking (false, removed)


#                     Web Application Group Configuration
# -----------------------------------------------------------------------------
app-group-config:
  primary:
    enabled: true
    table-name: smf_members
    user-id-column: id_member
    uses-key: false
    group-id-column: id_group

    key-name:
    key-column:

  secondary:
    enabled: true
    table-name: smf_members

    user-id-column: id_member

    storage-method: single

    group-id-column: additional_groups

    group-id-delimiter: ','

    key-name:
    key-column:

simple-synchronization:
  # Set this to true for simple synchronization
  enabled: true

  direction: minecraft

  # Set this to true if you want the player to be notified when their primary
  # group changes.
  primary-group-change-notify: false

  super-user-user-id: '1'

  groups-treated-as-primary: ['Guest','Member','Veteran','Elder']

  group-mapping:
    '12' : 'Guest'
    '11' : 'Member'
    '10' : 'Veteran'
    '9'  : 'Elder'

```

Also, when using '/cbsync' in game it returns 'null' to the player.
EDIT: Got bored and was messing around with github and this fixed the 'null' issue on my end. 
https://github.com/paul1338/CommunityBridge/commit/7c959428c7d64950601e312ac5766b28259fb593
